### PR TITLE
add moto e6plus

### PR DESCRIPTION
**Pull request by KatoTempest**
the overlay has slight changes in brightness and other values, the value assigned to vibration was set manually because the stock value was too low

### CODE REVIEW

**Comment by phhusson** [comment]
Good for me, you just need to pick a new priority, you can take 498

**Comment by KatoTempest** [comment]
I think I will try to reduce the manual brightness more, at night it bothers the view

**Comment by KatoTempest** [comment]
I had forgotten that I made the pull request, update my repository in case it has any conflict with the original branch (in case the overlay is accepted)

**Comment by phhusson** [comment]
please rebase your branch on top on phhusson:pie rather than merge

**Comment by KatoTempest** [comment]
I think I did the rebase correctly, it took a while due to the malfunction of my internet, although I don't see much difference in the repository

**Comment by phhusson** [comment]
The power_profile is obviously wrong. I'm removing it from https://github.com/TrebleDroid/vendor_hardware_overlay/. Open a new PR there to fix it.

**Pull request merged**
