### PR TITLE
Updated Redmi Note 10 5G / POCO M3 Pro/5G overlay

### PR DESCRIPTION
**Pull request by skittels15**

### CODE REVIEW

**Comment by phhusson** [comment]
What does this update do? Does it fix issues?

**Comment by skittels15** [comment]
Yes. Fixed and enabledsome device features

**Comment by phhusson** [comment]
like what?

**Comment by skittels15** [comment]
Fixed some WiFi and mobile network issues, default refresh rate and brightness levels.

**Pull request merged**
