### PR TITLE
Add Huawei COL Overlay

### PR DESCRIPTION
**Pull request by xiaoleGun**
Tested and running perfectly

### CODE REVIEW

**Comment by xiaoleGun** [comment]
Why not merge?

**Comment by phhusson** [comment]
Merged in https://github.com/phhusson/vendor_hardware_overlay/commit/31c49087d5b5ffe4bb914370cc7251a894950b84

**Comment by phhusson** [comment]
Merged in https://github.com/phhusson/vendor_hardware_overlay/commit/93a5ae7f277aa1a84aa06a82b2e0fe98a6439ee5

**Comment by phhusson** [comment]
You had COL *after* COR which is not correct alphabetical order

**Pull request closed without merging**
