### PR TITLE
Create Ulefone

### PR DESCRIPTION
**Pull request by gaijin213**

### CODE REVIEW

**Comment by phhusson** [comment]
Please send it to github.com/trebledroid/vendor_hardware_overlay

**Comment by gaijin213** [comment]
I am kinda lost to be honest on how to use your guide to create the overlays 😅

**Comment by lopestom** [comment]
> I am kinda lost to be honest on how to use your guide to create the overlays sweat_smile

https://github.com/Johx22/Overlay-builder
https://forum.xda-developers.com/t/guide-how-to-make-gsis-overlay-file-for-your-phone.3878974/
https://github.com/growtopiajaw/treble_experimentations/wiki/How-to-create-an-overlay%3F

**Comment by gaijin213** [comment]
Thanks but both very unclear still. Any video of the process please?

**Comment by lopestom** [comment]
> Thanks but both very unclear still. Any video of the process please?

Searching is your best frend........ :: ): 
If you not understand so not try.
Don't ask me, I not have your device in my hands.

**Pull request closed without merging**
