### PR TITLE
BV9500Plus: Back brightness values to stock; Add BV9800Pro overlay

### PR DESCRIPTION
**Pull request by Vgdn1942**

### CODE REVIEW

**Comment by phhusson** [comment]
Why?

**Comment by Vgdn1942** [comment]
> Why?

Now it is too dark outside and in other bright places.

**Comment by phhusson** [comment]
And this commit fixes it? It really shouldn't

**Comment by Vgdn1942** [comment]
> And this commit fixes it? It really shouldn't

Yes. This returns the stock brightness values.

**Pull request closed without merging**
