### PR TITLE
Add overlay for HuaweiEVA-AL10

### PR DESCRIPTION
**Pull request by jpourmalek**
it need to add this prop to vendor/build.prop
ro.hw.oemName=EVA-AL10

### CODE REVIEW

**Comment by phhusson** [comment]
Well if it needs to change vendor, then i don't want that.
Use a property available in vendor without modification.

Le mer. 11 déc. 2019 à 23:56, jpourmalek <notifications@github.com> a
écrit :

**Comment by barisdemirdelen** [comment]
Can we actually merge this? It works really well on my EVA-AL10 without any changes to /vendor

**Comment by phhusson** [comment]
Do you know why @jpourmalek said they needed to add that to their vendor/build.prop...?

**Comment by barisdemirdelen** [comment]
I don't know but my ro.hw.oemName is already EVA-AL10. I haven't changed it. Other huawei overlays also use ro.hw.oemName property.

if you like we can chane it to ro.vendor.build.fingerprint which starts with: HUAWEI/EVA-AL10

**Comment by phhusson** [comment]
And what does this overlay fix for you?

**Comment by barisdemirdelen** [comment]
Without is my battery life is around 1 hour and it gets very hot. I believe this overlay solves the issue

**Pull request closed without merging**
