### PR TITLE
Add support for the Huawei Y6 (2018)/Y6 Prime (2018)

### PR DESCRIPTION
**Pull request by TenSeventy7**
Adds appropriate power profile and minimum brightness setting to Huawei ATU-Lxx devices, the Y6 2018 (L21, L22, LX3) and Y6 Prime 2018 (L42).

### CODE REVIEW

**Comment by phhusson** [comment]
" 2018-12-28T02:23:24.0618365Z F: ./Huawei/msm8917/ATU/AndroidManifest.xml: priority 37 conflicts with another manifest "

You can run bash tests/tests.sh before submitting to run the tests on your side first.

**Comment by TenSeventy7** [comment]
I couldn't fix the conflicts, but priorities have been fixed.

**Comment by TenSeventy7** [comment]
> Why BKL

I was attempting to merge new changes, but I wasn't able to.
The ATU is already included in overlay.mk

**Comment by TenSeventy7** [comment]
I fixed it. :)

**Comment by phhusson** [comment]
I rebased/squashed your commits.
Check if everything still looks good to you

**Comment by TenSeventy7** [comment]
It looks good. Thank you so much!

**Pull request merged**
