### PR TITLE
Enable dt2w for begonia / Redmi Note 8 Pro

### PR DESCRIPTION
**Pull request by TTTT555**

### CODE REVIEW

**Comment by phhusson** [comment]
You've tested it?

**Comment by TTTT555** [comment]
> You've tested it?

A switch in the menu appeared, but the function does not work, additional edits are needed (the function worked in the Zaoda firmware).

**Comment by phhusson** [comment]
K so it doesn't work.

Have you tried dt2w setting in treble settings?

**Comment by TTTT555** [comment]
> K so it doesn't work. Have you tried dt2w setting in treble settings?

I don't see this setting in the menu (LineageOS 17.1)

**Comment by TTTT555** [comment]
Not needed with Xiaomi features in PHH Treble App

**Pull request closed without merging**
