### PR TITLE
Initial support for the LG V40 ThinQ

### PR DESCRIPTION
**Pull request by jamuir**
copy the LG G7 files and update Android.mk and AndroidManifest.xml.
The codename for the V40 is "judypn".

### CODE REVIEW

**Comment by jamuir** [comment]
from the kernel source for the LG V40, I see there are three judy devices:  `judypn, judyln, judyp`

**Comment by TadiT7** [comment]
You need the priority level to be 1 level higher than the last existing overlay, so wait for @phhusson merging my older PR and optionally of the guy after me. But the most important part is: V40 and G7 are totally different devices physically, so I'm pretty certain their notch size doesn't match. Find any actual owner first, or at least count from some full res screenshots of the stock ROM, like I sometimes need to do.

**Comment by jamuir** [comment]
nice auto-test :-)

Below all the "priority" values from the manifest files with `isStatic="true"`.

I guess I will use "54" rather than "15" to make this pass.

```
android:priority="3"
android:priority="6"
android:priority="10"
android:priority="11"
android:priority="12"
android:priority="13"
android:priority="14"
android:priority="15"
android:priority="15"
android:priority="16"
android:priority="17"
android:priority="18"
android:priority="19"
android:priority="21"
android:priority="22"
android:priority="25"
android:priority="26"
android:priority="27"
android:priority="28"
android:priority="29"
android:priority="31"
android:priority="32"
android:priority="33"
android:priority="34"
android:priority="35"
android:priority="36"
android:priority="37"
android:priority="38"
android:priority="39"
android:priority="40"
android:priority="41"
android:priority="43"
android:priority="44"
android:priority="45"
android:priority="46"
android:priority="47"
android:priority="48"
android:priority="49"
android:priority="50"
android:priority="51"
android:priority="53"
android:priority="9000"
```

**Comment by TadiT7** [comment]
Do yourself a black mockup with white bar on top until you get the exact notch height in pixels. I find the chance of exact same size as G7 rather impossible, but who knows...

**Comment by jamuir** [comment]
both devices have the same screen size:  3120 x 1440

https://www.lg.com/us/mobile-phones/v40-thinq/specs
https://www.lg.com/us/mobile-phones/g7-thinq/specs

for comparison, the V30 is different:

https://www.lg.com/us/cell-phones/lg-US998-Unlocked-v30

**Comment by TadiT7** [comment]
> both devices have the same screen size: 3120 x 1440
> 
> https://www.lg.com/us/mobile-phones/v40-thinq/specs
> https://www.lg.com/us/mobile-phones/g7-thinq/specs
> 
> for comparison, the V30 is different:
> 
> https://www.lg.com/us/cell-phones/lg-US998-Unlocked-v30

Notch size, rather than display resolution alone

**Comment by phhusson** [comment]
I'm merging this, but please follow up on @TadiT7's remarks.

Also:
> from the kernel source for the LG V40, I see there are three judy devices: judypn, judyln, judyp

Why are you matching only judypn then?

And do your vendor already contains a vendor/overlay/framework-res-rro-something apk?
Because your overlay seem very light. Usually the first thing people want are power profile and auto brightness

**Comment by jamuir** [comment]
thanks for merging.

I am having a difficult time measuring the notch using the method Tadi suggested.  I will try to figure something else out.

> Why are you matching only judypn then?

judypn, judyln, judyp all use the Qualcomm 845, but there are differences:

judy**pn** = LG V40 (**p**oled display, **n**otch)
judy**ln** = LG G7 (**l**cd display, **n**otch)
judy**p** = LG V35 (**p**oled display, no notch)

more info here:  https://www.xda-developers.com/lg-v40-thinq-snapdragon-845-poled-notch-google-assistant-button/

it might be possible to come up with a common overlay for the G7 and V40 eventually, but I am new at this and didn't want to break the G7.

> And do your vendor already contains a vendor/overlay/framework-res-rro-something apk?

No, there is no framework-res overlay on the V40.  I will look at adding power-profile and auto-brightness.

**Comment by phhusson** [comment]
> it might be possible to come up with a common overlay for the G7 and V40 eventually, but I am new at this and didn't want to break the G7.

No, if that's actually different devices, having one overlay per device is fine.

**Pull request merged**
