### PR TITLE
GSI fixes for Redmi 8 (olive)

### PR DESCRIPTION
**Pull request by skittels15**
Added basic fixes for Xiaomi Redmi 8 (olive) like as autobrightness, battery info per apps, audiojack and etc...

### CODE REVIEW

**Comment by phhusson** [comment]
Ci errors are that you need to add the overlay to overlay.mk and that you need to take another priority, this one is already taken

**Comment by skittels15** [comment]
> Ci errors are that you need to add the overlay to overlay.mk and that you need to take another priority, this one is already taken

Fixed. Try again please

**Comment by skittels15** [comment]
All issues fixed. Add my overlay to repo please

**Comment by phhusson** [comment]
And auto brightness works?

**Comment by skittels15** [comment]
> And auto brightness works?

All worked. All features ported from worked overlay

**Pull request merged**
