### PR TITLE
Fix led notifications lenovo s5

### PR DESCRIPTION
**Pull request by Mistrick**
Seems i wrongly understood this param and broke led

### CODE REVIEW

**Comment by phhusson** [comment]
What if you set this value to true? Is led still fixed in that case?

**Comment by Mistrick** [comment]
If it false we lose any LED settings in app notification settings.
I test LED with some apps and saw only blue color(if it true).

**Comment by TadiT7** [comment]
> What if you set this value to true? Is led still fixed in that case?

We set it to true by default, so deleting is the right action in this pr, by the way.

**Comment by Mistrick** [comment]
merge?

**Pull request merged**
