### PR TITLE
[Samsung Galaxy A51] Add auto-brightness for aod and mobile data fixed

### PR DESCRIPTION
**Pull request by nicovanoo**

### CODE REVIEW

**Comment by phhusson** [comment]
I'm confident this PR doesn't do what it says it do, but I can merge it if that makes you happy

**Comment by nicovanoo** [comment]
This overlay update adds aod Auto brightness and fixes mobile data broken by first overlay (forgot to add add)

**Comment by phhusson** [comment]
Pretty sure it doesn't, but if this makes you happy I can merge it.

**Comment by nicovanoo** [comment]
Yeah it does, but for the A52 and not for the A51, for the A51 I tested something but didn't make a difference, I'll close this pull request and open a new one when changes to A51 overlay are reverted

**Pull request closed without merging**
