### PR TITLE
B2N: overlay: Fix rounded_corner_radius

### PR DESCRIPTION
**Pull request by raysenlau**
Screen rounding set to 16dp would be a good fit

### CODE REVIEW

**Comment by phhusson** [comment]
Uh you're really sure it works? 
As far as I know this property should be set in an overlay for SystemUI not framework-res

**Comment by raysenlau** [comment]
> Uh you're really sure it works?
> As far as I know this property should be set in an overlay for SystemUI not framework-res

Yes, it works, I have tested it on PE.

**Comment by raysenlau** [comment]
Similar to this commit：
https://github.com/phhusson/vendor_hardware_overlay/commit/52424fab69a148053484f8b46d108f0a390c3a45

**Comment by TadiT7** [comment]
> Uh you're really sure it works?
> As far as I know this property should be set in an overlay for SystemUI not framework-res

Nah, there's `rounded_corner_radius` in framework-res, we are using that. What's SystemUI-exclusive is only the padding.

**Comment by TadiT7** [comment]
Rebase on the current master branch please.

**Pull request closed without merging**
