### PR TITLE
Change config.xml to support VoLTE

### PR DESCRIPTION
**Pull request by khrj**
Redmi 7A Supports VoLTE with https://github.com/KhushrajRathod/VoLTE-Fix

### CODE REVIEW

**Comment by phhusson** [comment]
What does this overlay actually fix?

There is nothing device-specific in there.

**Comment by KhushrajRathod** [comment]
It's not possible to use VoLTE without using this overlay. I used the Ims-q apk and android.hardware.telephony.ims.xml along with this overlay change to enable VoLTE

**Comment by phhusson** [comment]
That's weird, no other device require it
All devices go just fine with https://github.com/phhusson/vendor_hardware_overlay/blob/master/CAF-IMS/res/values/config.xml

Perhaps the issue is that those flags are in this overlay in the first place? I don't know who put them there and why

Also, `config_wifi_dual_band_support` has nothing to do with VoLTE.

**Comment by KhushrajRathod** [comment]
Will remove flags completely and check VoLTE function, then revert back to you

**Comment by KhushrajRathod** [comment]
Nope, completely removing the flags disables VoLTE. The flags are required for VoLTE to function.

**Comment by KhushrajRathod** [comment]
I've changed the config_wifi_dual_band_support flag

**Comment by KhushrajRathod** [comment]
Please merge

**Comment by phhusson** [comment]
Did the equivalent in f4e0df4

Thanks for bringing up this issue.

**Pull request closed without merging**
