### PR TITLE
Add statusbar height to cover the notch on Asus ZenFone 5

### PR DESCRIPTION
**Pull request by TadiT7**

### CODE REVIEW

**Comment by TadiT7** [comment]
sorry, forgot about adding to the build list xD

**Comment by phhusson** [comment]
You forgot the overlay.mk :p

Le 14 juin 2018 23:17, "Tadi" <notifications@github.com> a écrit :

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/phhusson/vendor_hardware_overlay/pull/4
Commit Summary

   - Add statusbar height to cover the notch on Asus ZenFone 5

File Changes

   - *A* Asus/ZenFone5/Android.mk
   <https://github.com/phhusson/vendor_hardware_overlay/pull/4/files#diff-0>
   (7)
   - *A* Asus/ZenFone5/AndroidManifest.xml
   <https://github.com/phhusson/vendor_hardware_overlay/pull/4/files#diff-1>
   (10)
   - *A* Asus/ZenFone5/res/values-land/notch.xml
   <https://github.com/phhusson/vendor_hardware_overlay/pull/4/files#diff-2>
   (22)
   - *A* Asus/ZenFone5/res/values/notch.xml
   <https://github.com/phhusson/vendor_hardware_overlay/pull/4/files#diff-3>
   (22)

Patch Links:

   - https://github.com/phhusson/vendor_hardware_overlay/pull/4.patch
   - https://github.com/phhusson/vendor_hardware_overlay/pull/4.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/phhusson/vendor_hardware_overlay/pull/4>, or mute the
thread

**Comment by TadiT7** [comment]
Wait, I'm a nub, but what's increment priority?

**Comment by TadiT7** [comment]
It's right at 14

**Comment by phhusson** [comment]
Oh. I'd swear I'd seen it was 13 in your commit

**Pull request merged**
