### PR TITLE
Add overlay for Samsung Galaxy A02s

### PR DESCRIPTION
**Pull request by mrugtangy**

### CODE REVIEW

**Comment by mrugtangy** [comment]
I removed a device by mistake in overlay.mk in the first commit and added it back in the second one.

**Comment by phhusson** [comment]
That's a very light power profile. Did you check that it works at least a bit?

**Comment by tangymc** [comment]
> That's a very light power profile. Did you check that it works at least a bit?

Yep it does work.

**Comment by mrugtangy** [comment]
> That's a very light power profile. Did you check that it works at least a bit?

Works perfectly. And I also found it in the device's framework-res.apk (vendor) and it contains the right configs for the device.

**Comment by mrugtangy** [comment]
Pls pull 🙂

**Pull request closed without merging**
