### PR TITLE
Overlay for Vsmart Live (V620A), Fix AOD

### PR DESCRIPTION
**Pull request by trinhloi**
Fix AOD,Brightness,Fingerprint

### CODE REVIEW

**Comment by phhusson** [comment]
Stop spamming.

**Comment by trinhloi** [comment]
> Stop spamming.

sorry sir, this is my first time createoverlay. i understand how it works

**Comment by phhusson** [comment]
Feel free to do whatever you want in this merge request.
But DO NOT create a new one. YOU DON'T NEED to make a new one
.

**Comment by trinhloi** [comment]
> Feel free to do whatever you want in this merge request. But DO NOT create a new one. YOU DON'T NEED to make a new one

thank sir, i got it

**Comment by trinhloi** [comment]
@phhusson It is ready to be shipped, sir
I have checked and it works on my device
Please add this
thank you

**Pull request merged**
