### PR TITLE
Add overlay for Realme C1

### PR DESCRIPTION
**Pull request by Tuan9304**
Initial commit

### CODE REVIEW

**Comment by phhusson** [comment]
Have you actually tested it?
In my experience, `ro.vendor.build.fingerprint` doesn't work on Oppo devices

**Comment by Tuan9304** [comment]
Oh sorry I don't know that. Do you have any idea? Can I use `ro.hw.oemName`?

**Comment by Tuan9304** [comment]
It works fine now

**Comment by Tuan9304** [comment]
My pull request to fix brightness: https://github.com/phhusson/device_phh_treble/pull/165

**Comment by phhusson** [comment]
Auto brightness values are pretty fishy. Have you actually tested it?

**Comment by Tuan9304** [comment]
Yes, it work too. There are `<"config_autoBrightness...">` & `<"config_tenbit_autoBrightness...">` & `elevenbit` and `twelvebit`. 
I tried `config_autoBrightness` with max value is 255 but it not work correctly (brightness so dark when not maximized) so I tried `elevenbit` with the same max brightness value with max_brightness file and it works well.

**Comment by Tuan9304** [comment]
It seems everything is fine. I can't test voLTE because my carrier doesn't support it.

**Pull request closed without merging**
