### PR TITLE
Enable the navigation bar for Mi A2

### PR DESCRIPTION
**Pull request by jackwakefield**
This is currently missing for Pie.

### CODE REVIEW

**Comment by TadiT7** [comment]
What https://github.com/phhusson/vendor_hardware_overlay/blob/08c4ef3d9c851bc27e625be3a685482c434d975b/Xiaomi/MiA2/res/values/config.xml#L32 has to do with navbar?

**Comment by jackwakefield** [comment]
Whoops, that was meant to be removed (and is now).

**Comment by phhusson** [comment]
config_supportSystemNavigationKeys has nothing to do with navbar (yeah thanks Google for that helpful naming.)
This is fingerprint sensor gestures (swipe up/down on fingerprint sensor to show/hide notifications)

Is this intended?

**Comment by jackwakefield** [comment]
Ah, I had included config_supportSystemNavigationKeys because I thought it was to do with the navbar (thanks for the heads up), so it could be removed at least from this PR, but it is in the Pie ROM's config.

On the other hand, I haven't yet had any luck getting the fingerprint reader to work on the Mi A2, but I haven't investigated that yet and it could just be an issue on my end.

I'm happy to take your advice on whether to remove it or separate it out into a new PR.

**Comment by phhusson** [comment]
merged in https://github.com/phhusson/vendor_hardware_overlay/commit/1643f1d9fd13b1e37feeadca558f08dbc11b19c5

**Pull request closed without merging**
