### PR TITLE
Redmi7A: Disable rounded corners

### PR DESCRIPTION
**Pull request by YaAlex3**
its temporary, I don't know why roundness is too big tbh.

### CODE REVIEW

**Comment by phhusson** [comment]
uh 106px indeed sounds very high, i'm more used to 26px
You can set it in treble app, so is there a point in removing it...?

**Comment by YaAlex3** [comment]
i don't know honestly about normal values, but in miui framework was these values.

**Comment by YaAlex3** [comment]
also is there any ways we can measure that?

**Comment by YaAlex3** [comment]
any updates on this?
looks like i can't disable those in app..

**Pull request merged**
