### PR TITLE
Added Xiaomi Redmi Note 9S Overlay

### PR DESCRIPTION
**Pull request by TuxKruger**
Since you couldn't merge #217 by @sooti, I am opening a new PR with his fixes again. All commits are authored by @sooti (I couldn't merge https://github.com/phhusson/vendor_hardware_overlay/pull/217/commits/d587d9ad4cb00d8966feed971381dcb885c6e66b so I made the changes myself). I apologize if I made any mistakes, this is the first time I cherry picked someone else's commits.

### CODE REVIEW

**Comment by phhusson** [comment]
Fatal: ./Xiaomi/RedmiNote9Pro: Overlay ./Xiaomi/RedmiNote9Pro is defining config_swipe_up_gesture_setting_available which is forbidden
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_enableLockBeforeUnlockScreen
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_primarycard
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_smart_battery_available
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_sms_authorization_enabled
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_swipe_up_gesture_setting_available
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_useDefaultFocusHighlight
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_useMasterVolume
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_useVolumeKeySounds
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_user_notification_of_restrictied_mobile_access
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_wifi_disconnect_only_on_initial_ipreachability
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_wifi_dual_sap_mode_enabled
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_wifi_framework_secondary_sta_supported
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_wifi_report_he_ready
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_wifi_softap_acs_should_exclude_dfs
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_wifi_softap_ieee80211ax_supported
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_wifi_wap3_sap_mode_enabled
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute useImsAlwaysForEmergencyCall
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_MaxConcurrentDownloadsAllowed
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_attentionMaximumExtension
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_criticalBatteryWarningLevel
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_downloadDataDirSize
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_dozeWakeLockScreenDebounce
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_lowBatteryCloseWarningLevel
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_lowMemoryWarningValue
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_releaseMemoryLimit
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_sms_authorization_timeout_ms
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_virtualKeyQuietTimeMillis
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute data_retry_delay
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute data_retry_idle_delay
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute resumeboost_timeout_param
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute wifi_hotspot_security_type
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute config_wifi_dual_sap_interfaces
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute fingerprint_acquired_vendor
Fatal: ./Xiaomi/RedmiNote9Pro/res/values/config.xml: defines a non-existing attribute low_lux_level
Fatal: ./Xiaomi/RedmiNote9S: Overlay ./Xiaomi/RedmiNote9S is defining config_swipe_up_gesture_setting_available which is forbidden
Fatal: ./Xiaomi/RedmiNote9ProMax/res/values/config.xml: defines a non-existing attribute wifi_hotspot_security_type
Fatal: ./Xiaomi/RedmiNote9ProMax/res/values/config.xml: defines a non-existing attribute config_wifi_dual_sap_interfaces
Fatal: ./Xiaomi/RedmiNote9ProMax/res/values/config.xml: defines a non-existing attribute fingerprint_acquired_vendor
Fatal: ./Xiaomi/RedmiNote9ProMax/res/values/config.xml: defines a non-existing attribute low_lux_level

**Comment by sooti** [comment]
You mean those are xiaomi values? odd... guess you can remove those

**Comment by TuxKruger** [comment]
gotta remove more values. :(

**Comment by TuxKruger** [comment]
Finally, all checks passed. @phhusson you can merge now, right? Sorry for so many commits for the stuff that could have been done in lesser commits.

**Comment by Aarqw12** [comment]
I have generated overlay redminote9s and put to system/product/overlay/ permissions file 644 .

despite after Reboot its isn't give any effects ...

**Pull request closed without merging**
