### PR TITLE
[Redmi 9] Added brightness arrays for Q/R vendor and some changes

### PR DESCRIPTION
**Pull request by ghost**
This is needed for someone who prefers to use Q/R vendor over S vendor (like me).
Because i think Q/R vendor is smoother than S vendor.
Unfortunately adaptive brightness doesn't work if you're on A13 with Q/R vendor.
And most likely this will be the last PR for Redmi 9 (no more updates from Xiaomi)

Changes:

- Added brightness arrays for Q/R vendor.
- Removed **config_useDevInputEventForAudioJack** from overlays.
- Re-added values-xxhdpi into SystemUI. (Let system choose the best)
- Add a newline at end of file (the original file has a newline at the end)

> Brightness arrays is to make auto brightness work on Q/R vendor.

> Remove **config_useDevInputEventForAudioJack**
> Why?
> Opening Treble App even without making any changes triggers changes to the overlay.
>  
> ```
> adb shell getprop | grep overlay
> [persist.sys.overlay.aod]: [false]
> [persist.sys.overlay.devinputjack]: [false]
> [persist.sys.overlay.minimal_brightness]: [false]
> [persist.sys.overlay.nightmode]: [true]
> ```
> 
> As you can see:
> `[persist.sys.overlay.devinputjack]: [false]` causes input jack to stop working.
> And if the input jack doesn't work it will trigger brightness slider (with adaptive brightness enabled) not work properly.
> With or without config_useDevInputEventForAudioJack in the end I still have to use TrebleApp.
> So, better to use **Treble App** in the first place and enable **Use alternate way to detect headsets** & **Force alternative backlight scale**.

Tested

### CODE REVIEW

**Comment by phhusson** [comment]
You say brightness but it changes a lot of unrelated things...

**Comment by ghost** [comment]
> You say brightness but it changes a lot of unrelated things...

[Updated](https://github.com/phhusson/vendor_hardware_overlay/pull/687#issue-1506302083)

**Comment by ghost** [comment]
Sir @phhusson 
could you review this pull request again?
i did a force pushed five days ago and had no issues so far.
[overlay changes](https://github.com/phhusson/vendor_hardware_overlay/pull/687#issue-1506302083)
thank you.

**Comment by ghost** [comment]
I tested Q vendor with AOSP 12.1, AOSP 13, LOS 19.1, LOS 20 TD/Light
Q vendor is even smoother compared to R vendor and S vendor.
And more importantly, Q vendor doesn't have any issues related to eBPF (internet in power saving mode, traffic control).

Unfortunately, like R vendor, Q vendor also lack auto brightness.
This PR will solve the problem.
And most likely this will be the last PR for Redmi 9
Please merge sir @phhusson , thank you!

**Pull request closed without merging**
