### PR TITLE
Add resources for some xiaomi (longcheer's odm) devices

### PR DESCRIPTION
**Pull request by suwakowww**
I think it can fix 
phhusson/treble_experimentations#226 and phhusson/treble_experimentations#229
for:
- wayne (tested and working)
- jasmine (blind-patched)
- sakura (blind-patched)
- daisy (blind-patched)
- nitrogen (blind-patched)
- whyred (blind-patched)

### CODE REVIEW

**Comment by suwakowww** [comment]
Seems works on 6x now, but I don't know why should write in lower case letters.
referrer: 
https://github.com/TadiT7/xiaomi_wayne_dump/blob/CORRUPTED---wayne-user-8.1.0-OPM1.171019.011-8.7.12-release-keys/vendor/build.prop#L5
https://github.com/TadiT7/xiaomi_jasmine_dump/blob/jasmine-user-8.1.0-OPM1.171019.011-8.9.20-release-keys/vendor/build.prop#L5

**Comment by coderzstas** [comment]
Shipit

**Comment by mesilliac** [comment]
works for me on daisy (tested on an android-9.0 vanilla-nosu build)

there was a conflict merging with the `pie` branch, but resolution was trivial given the last two commits that touched overlay.mk so i just did it manually to test

**Comment by vroomr** [comment]
Any way I can test this on Jasmine?

**Comment by vroomr** [comment]
Minimum brightness and auto brightness also working on Jasmine

**Comment by phhusson** [comment]
Sound good to me.

Did you check the lower/upper case mess for all devices?

**Comment by suwakowww** [comment]
I checked it already since commit `97c4690`, but it can match for lower/upper case now, just change `Xiaomi` and `xiaomi` to `*iaomi`

**Comment by phhusson** [comment]
Merged in https://github.com/phhusson/vendor_hardware_overlay/commit/6e16df7d8980983b4d979f4b371a44588d0fcbc2
with some additional fixes ( https://github.com/phhusson/vendor_hardware_overlay/commit/580da1d8a644dee9c4b22cfd9e14298e20a19111 )

Thanks

**Pull request closed without merging**
