### PR TITLE
Update power_profile.xml for Xiaomi Mi A2

### PR DESCRIPTION
**Pull request by jackwakefield**
Copied from the stock ROM by kdrag0n https://gist.github.com/kdrag0n/c766d0a34d6d39112c5d8e541e8baab7)

### CODE REVIEW

**Comment by TadiT7** [comment]
Is it Pie or Oreo file?

**Comment by jackwakefield** [comment]
This is from the Pie (V10.0.2.0.PDIMIFJ) update, I've just extracted it myself to be sure.

**Comment by TadiT7** [comment]
Then as far as my understating goes, we can only merge it to pie branch @phhusson

**Comment by jackwakefield** [comment]
Thanks for the heads up, I've created #76

**Pull request closed without merging**
