### PR TITLE
Add overlay for Samsung Galaxy M11

### PR DESCRIPTION
**Pull request by arijit192**
Adding overlay for Samsung Galaxy M11 (SM-M115F)

### CODE REVIEW

**Comment by phhusson** [comment]
Looks good to me. Have you tested it?

**Comment by arijit192** [comment]
I could not transfer the files to /system/product/overlay because the root is read-only. I tried to make /dev/block/dm-0 readwrite by blockdev but no luck. I also tried to modify system.img by mounting it to my PC but still no luck. Can you please suggest some workarounds?

**Comment by phhusson** [comment]
Did you flash vndklite variant?

Le sam. 19 juin 2021 à 11:17, Arijit Roy ***@***.***> a
écrit :

**Comment by arijit192** [comment]
No. This one system-roar-arm32_binder64-ab-gapps.img.xz

**Comment by phhusson** [comment]
Well, with the nvdklite variant it'll be easier to mount / rw

Le dim. 20 juin 2021 à 03:40, Arijit Roy ***@***.***> a
écrit :

**Comment by arijit192** [comment]
Okay thanks. I will test it ASAP and let you know

**Comment by arijit192** [comment]
I have tested the vendor overlay. As per my testing, some things are not working like WiFi calling, VoLTE, MTP and no sound of voice when on audio call. Other than that everything is working fine.

**Comment by phhusson** [comment]
Ok, but what does the overlay fix?

20 juin 2021 19:04:24 Arijit Roy ***@***.***>:

**Comment by arijit192** [comment]
After observing well I noticed very little changes like the auto brightness is working a little better and notch management seems to be better. Apart from that I have not seen any huge difference between overlay and without overlay. Without overlay the device is working just fine except the above things that I mentioned in comment are broken.

**Pull request merged**
