### PR TITLE
add galaxy tab s8 overlay

### PR DESCRIPTION
**Pull request by thefiredragon**

### CODE REVIEW

**Comment by phhusson** [comment]
automatic brightness has been tested?

**Comment by thefiredragon** [comment]
automatic brightness is working, 
but unlike on other device here I need to set scale value to 255 in phh settings,
on all other device only needed to enable extend brightness range under  settings / trebleapp / samsung / 
Can I preset "Set backlight scale/max" backlight level?

**Comment by phhusson** [comment]
Sure there is https://github.com/phhusson/treble_presets/ to preset stuff

**Comment by phhusson** [comment]
Can I merge it now or do you still want to change stuff?

**Comment by thefiredragon** [comment]
yes you can thank you, i'll take a look there

**Pull request merged**
