### PR TITLE
Add resources for Xiaomi Redmi K20 Pro (raphael)

### PR DESCRIPTION
**Pull request by AndyCGYan**
Numerical values taken directly from device; bool values set based on other devices (Mi 8, Mi Mix 3).
I can confirm that this at least fixes auto brightness, not sure what else.
Since this is my first PR ever on GitHub, if I made any mistakes, or if there's something wrong within the changes themselves, please let me know.

### CODE REVIEW

**Comment by phhusson** [comment]
CI not happy
```
2019-06-03T12:51:20.8472323Z F: ./Xiaomi/RedmiK20Pro/res/values/config.xml: defines a non-existing attribute config_dozeAlwaysOnEnabled
```

**Comment by AndyCGYan** [comment]
> CI not happy
> 
> ```
> 2019-06-03T12:51:20.8472323Z F: ./Xiaomi/RedmiK20Pro/res/values/config.xml: defines a non-existing attribute config_dozeAlwaysOnEnabled
> ```

Jeez, build.sh didn't complain about this.
But why though? Isn't this an existing prop in AOSP?

**Comment by phhusson** [comment]
That's tests/tests.sh

This values does exist in AOSP, but there is no point in overlay-ing it,
it's true by default.
The use of this value is for ROMs that consider than AOD should be disabled
by default, it doesn't change the capability of the firmware to optionally
do AOD

**Comment by phhusson** [comment]
It's not build that was broken, but tests :p

**Comment by AndyCGYan** [comment]
> It's not build that was broken, but tests :p

I hate GitHub Desktop for not letting me amend commits >:(

**Comment by AndyCGYan** [comment]
Er. what? Is it a requirement to use continuous priority numbers? But I sorted the existing list and I swear I saw not-continuous ones...

**Comment by phhusson** [comment]
Nope
Issue is ```
F: ./Moto/G7Power/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
```
so that's not you (I need to fix it though. I thought i already did).

Let's say CI is green.

Now we're waiting for @TadiT7 approval who has much better eyes than me for overlays.

**Comment by AndyCGYan** [comment]
> Nope
> ...
> so that's not you (I need to fix it though. I thought i already did).
> 
> Let's say CI is green.
> 
> Now we're waiting for @TadiT7 approval who has much better eyes than me for overlays.

Thanks, waiting.
P.S. Fix the comment lol

**Comment by TadiT7** [comment]
`<dimen name="status_bar_height_portrait">74px</dimen>` will do.

**Comment by AndyCGYan** [comment]
> Seems clean, but I recommend to use a bigger statusbar, since it's quite a long device and OEMs now tend to make them bigger on such, even without any kind of a notch.
> Let's say 32dp would be nice, or at least the Google's 28dp.

Gotcha. Seems I need to create a separate SystemUI overlay for it.
28/32dp doesn't sound too drastic compared to the default 24dp, though I'll have to see it for myself, not a fan of too-big statusbar after using some notched devices.
Also, mind if I add `rounded_corner_content_padding` as well?

**Comment by TadiT7** [comment]
> > Seems clean, but I recommend to use a bigger statusbar, since it's quite a long device and OEMs now tend to make them bigger on such, even without any kind of a notch.
> > Let's say 32dp would be nice, or at least the Google's 28dp.
> 
> Gotcha. Seems I need to create a separate SystemUI overlay for it.
> 28/32dp doesn't sound too drastic compared to the default 24dp, though I'll have to see it for myself, not a fan of too-big statusbar after using some notched devices.
> Also, mind if I add `rounded_corner_content_padding` as well?

Actually, statusbar size is the fwb part, while rounded corner content padding is only available through SystemUI. But 28dp will be fine, it doesn't look "notched" :)

**Comment by AndyCGYan** [comment]
@TadiT7 Is it okay if I fix up (amend) the commit history and force push? Will that affect how the PR works?

**Comment by AndyCGYan** [comment]
@TadiT7 Can you inspect the newly added SystemUI overlay please? It doesn't seem to get applied, at least on LOS.
It's possible though that it's an LOS-specific bug, in which case I'll just leave the overlay here and manually apply the padding on my device via ADB command.

**Comment by phhusson** [comment]
SystemUI overlays need to be explicitly enabled, usually from treble app
This is annoying, so I simply added a parameter in treble settings so the
user can set its own rounded corners value.
Though if you do the relevant MR to treble app I can still merge it

**Comment by AndyCGYan** [comment]
> SystemUI overlays need to be explicitly enabled, usually from treble app This is annoying, so I simply added a parameter in treble settings so the user can set its own rounded corners value. Though if you do the relevant MR to treble app I can still merge it

That sucks. Guess I'll just undo the SystemUI overlay.
Also, as I asked Tadi as well, can I do force push to correct commit history and such? Will it mess up this PR?

**Comment by phhusson** [comment]
Yeah if you want

**Comment by AndyCGYan** [comment]
Ugh, I just realized that I made changes on `master` instead of `pie`...

**Comment by phhusson** [comment]
Yeah that works don't worry, I rebase pie on top of master for every
release.
(Except this month because I failed)

**Comment by AndyCGYan** [comment]
> Yeah that works don't worry, I rebase pie on top of master for every release.

So I should actually switch the base back to `master`?

**Comment by phhusson** [comment]
Both work

**Comment by AndyCGYan** [comment]
OK, waiting on merge/rebase.

**Comment by TadiT7** [comment]
px is the right way because it stays the same.

**Comment by AndyCGYan** [comment]
> px is the right way because it stays the same.

Per PHH's reply I just ditched the SystemUI overlay altogether. Thanks for letting know though.

**Pull request merged**
