### PR TITLE
Change android:requiredSystemPropertyValue

### PR DESCRIPTION
**Pull request by Johx22**

### CODE REVIEW

**Comment by phhusson** [comment]
why?

**Comment by Johx22** [comment]
> why?

The device codename is actually 2026. @rthelolchex confirmed it for me. Since my device is bricked I couldn't confirm it.

**Comment by rthelolchex** [comment]
Screenshot_20220314-234046_Termux~2

yeah i have the phone in here, the codename is not y20, it's 2026

**Comment by phhusson** [comment]
So the overlay that has been merged hadn't been tested?

**Comment by rthelolchex** [comment]
i'm building aosp rn, and i will trying it

**Comment by Johx22** [comment]
> So the overlay that has been merged hadn't been tested?

Tested by @rthelolchex by I forgot to push the commit while publishing.

**Comment by rthelolchex** [comment]
> > So the overlay that has been merged hadn't been tested?
> 
> Tested by @rthelolchex by I forgot to push the commit while publishing.

@johx22 send us the correct overlay but seems he didn't push this commit to the Branch.

**Pull request merged**
