### PR TITLE
add Qin 2 Pro from DuoQin

### PR DESCRIPTION
**Pull request by PeterCxy**

### CODE REVIEW

**Comment by phhusson** [comment]
I'll allow

wifi_tether_configure_ssid_default, wifi_localhotspot_configure_ssid_default and config_bluetooth_max_connected_audio_devices

However, could you explain to me why you want to set config_notificationsBatteryMediumARGB to green? medium battery level shouldn't be green

**Comment by PeterCxy** [comment]
I'm pretty sure 0xFFFF0000 is red tho...

**Comment by phhusson** [comment]
ah right sorry.
Still full red for medium is weird

**Comment by PeterCxy** [comment]
nvm, that's probably just something I forgot to delete from official overlay. I don't think this LED is even RGB

**Comment by PeterCxy** [comment]
removed

**Pull request merged**
