### PR TITLE
Add pdx213 overlay

### PR DESCRIPTION
**Pull request by pepijndevos**
Currently untested draft. I'll update later with my findings.
Combines files from https://github.com/sonyxperiadev/device-sony-common and https://github.com/sonyxperiadev/device-sony-pdx213

### CODE REVIEW

**Comment by phhusson** [comment]
Ok, let's go over CI errors:
```
Fatal: ./Sony/pdx213: Overlay ./Sony/pdx213 is defining config_useRoundIcon which is forbidden
Fatal: ./Sony/pdx213: Overlay ./Sony/pdx213 is defining config_swipe_up_gesture_setting_available which is forbidden
Fatal: ./Sony/pdx213: Overlay ./Sony/pdx213 is defining config_cellBroadcastAppLinks which is forbidden
Fatal: ./Sony/pdx213: Overlay ./Sony/pdx213 is defining config_dozeComponent which is forbidden
Fatal: ./Sony/pdx213: Overlay ./Sony/pdx213 is defining config_enableAutoPowerModes which is forbidden
Fatal: ./Sony/pdx213: Overlay ./Sony/pdx213 is defining config_enableMultiUserUI which is forbidden
Fatal: ./Sony/pdx213: Overlay ./Sony/pdx213 is defining config_multiuserMaximumUsers which is forbidden
```
So those are forbidden because it is a ROM thingy, not a hardware thingy. It's normal that Sony set them for a clean AOSP ROM, it's just not for us.

`Fatal: ./Sony/pdx213/AndroidManifest.xml: priority 454 conflicts with another manifest`
For stupid reasons (Google bug) we need each manifest have different values, you need to pick another one. CI recommends 365

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_biometric_sensors`
Ok i'll allow this one. I set it ROM-side, but it's really a HW thingy.

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_unplugTurnsOnScreen`
That's up to the ROM, not HW stuff

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_cellBroadcastAppLinks`
Same

```
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_wifi_softap_acs_supported
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_wifi_softap_acs_supported_channel_list
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_wifi_softap_ieee80211ac_supported
```

Those are HW things, I could allow them, however in Android 12 they are no longer set here, but somewhere else (`Wifi` overlay). So for the moment let's remove it


`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_locationProviderPackageNames`
That's a ROM thingy

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_enableWifiDisplay`
Uh that's a tough one. I'm pretty confident wifi display is broken on AOSP, so I'd rather not set it, but if you test it and tell me it works, I'll allow it.

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_mms_user_agent`
I'll not consider this a HW setting, so let's remove it

```
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_multiuserMaximumUsers
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_enableMultiUserUI
```
This is a ROM setting, not related to HW

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_batterySdCardAccessibility`
I'll allow it, even though on my GSI it shouldn't change anything.

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_enableAutoPowerModes`
That's 100% a ROM setting, because depending whether you use Gapps (or other push services), or not you'll want different settings.

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_wifi_tcp_buffers`
Well this is dead in Android 12, and anyway I don't consider this to be HW-specific (though that's debatable)

```
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_useRoundIcon
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_icon_mask
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_defaultDndAccessPackages
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_smart_battery_available
```
Those are 100% not hw-related and purely up to ROM's choice

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_carrier_vt_available`
That's not HW-specific

```
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_wlan_data_service_package
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_wlan_network_service_package
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_qualified_networks_service_package
```
This one is annoying, but I guess I'll allow it.

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_dozeComponent`
No HW specific

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_dozeAlwaysOnEnabled`
Considering this is an OLED device, this is a ROM choice, not a HW-specific setting

`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_mms_user_agent_profile_url`
ROM stuff not HW I believe

```
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute doze_display_state_supported
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute doze_suspend_display_state_supported
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute doze_double_tap_reports_touch_coordinates
```
This is in SystemUI, not frameworks-res

```
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute doze_pickup_performs_proximity_check
```
Doesn't exist in Android 12


`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_statusBarBurnInProtection`
Doesn't exist in Android 12
`Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_shift_interval`
Doesn't exist in Android 12

**Comment by pepijndevos** [comment]
`config_enableWifiDisplay` I have no TV to test this with, removed.

`config_wifi_tcp_buffers` I assume same goes for `config_mobile_tcp_buffers`? Arguably not HW specific, removed.

`config_carrier_vt_available` I assume same goes for `config_carrier_volte_available`, so both removed. Can't say I really understand the implications. Comment seems to imply it just allows it to be used if the carrier allows it, while otherwise it's hard disabled despite the device having it?

`config_wlan_data_service_package` All the ones that have packages in them, whether they are allowed or not, are most likely completely useless on AOSP right? I'll leave them for now.

`config_dozeComponent` there is lots of `doze*` stuff, is all of it bunk? There are some you didn't mention, but maybe all of it can go.

> This is in SystemUI, not frameworks-res

Should all of SystemUI go? I manly copied it because the burn-in protection parts.

**Comment by pepijndevos** [comment]
So if I understand you correctly you will add these remaining properties to the allowlist?
```
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_biometric_sensors
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_batterySdCardAccessibility
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_wlan_data_service_package
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_wlan_network_service_package
Fatal: ./Sony/pdx213/res/values/config.xml: defines a non-existing attribute config_qualified_networks_service_package
Note: First high continuous priority available is 950
	I recommend you use priority 405
```

**Comment by pepijndevos** [comment]
I can't figure out how to upload this overlay.
I used
```
adb root
adb remount
adb push build/treble-overlay-sony-pdx213.apk /system/overlay/treble-overlay-sony-pdx213.apk
```

but the file just disappears after rebooting.

My phone does not have a `/system/vendor` folder, and no `/system` mountpoint at all it seems.
It does have `/vendor/overlay` but when I try to remount that rw it tells me `'/dev/block/dm-4' is read-only`

How/where can I actually upload this overlay?

Running `mount` spews a lot of crap about `/sbin/.magisk/block/system_root` so maybe there is a special "Magisk" way to add overlays?

**Comment by pepijndevos** [comment]
Pfffff I've created a Magisk module which is apparently the way to do it.
Except my file still doesn't show up.
[overlaymod.zip](https://github.com/phhusson/vendor_hardware_overlay/files/7538230/overlaymod.zip)

```
XQ-BT52:/ # ls /data/adb/modules/mystupidoverlay/                                                                                                       
module.prop  system
XQ-BT52:/ # ls /data/adb/modules/mystupidoverlay/system/overlay/treble-overlay-sony-pdx213.apk                                                          
/data/adb/modules/mystupidoverlay/system/overlay/treble-overlay-sony-pdx213.apk
XQ-BT52:/ # ls /system
addon.d  app  build.prop  fonts      lib    media  phh       product     usr     xbin
apex     bin  etc         framework  lib64  ph     priv-app  system_ext  vendor
XQ-BT52:/ # 
```

**Comment by pepijndevos** [comment]
Haha yes!!!

Screenshot_20211115-124815_LineageOS_Settings
[overlaymod.zip](https://github.com/phhusson/vendor_hardware_overlay/files/7538412/overlaymod.zip)

The trick was to put it in `/system/vendor/overlay` for some reason.

**Comment by yiesko** [comment]
`/system/vendor` is a symlink for `/vendor` (O+)

**Comment by pepijndevos** [comment]
Yea I read that on the Magisk documentation, I'm just not sure why that worked, but `/system/overlay` did not. Anyway, the overlay seems to work as far as I can tell. Just let me know if I need to change anything or if there are any tests I need to do to confirm more features.

**Comment by pepijndevos** [comment]
I have added all the properties of which @phhusson said "I'll allow it" to the `knownKeys` so now the tests pass. If this was not what was intended, let me know and I'll revert it and remove the keys instead.

**Comment by pepijndevos** [comment]
This PR is now superseded by #423 which took these files but removed the tricky keys instead of adding them to the list. Bit sad I did not get any feedback on my PR but happy my overlay got merged somehow.

**Pull request closed without merging**
