### PR TITLE
Add the Samsung A20 to the vendor_hardware_overlay

### PR DESCRIPTION
**Pull request by tristanbollard**
Made pretty much with a SM-A205YN's vendor partition and system partitions... also has been tested and it's made an improvement.

### CODE REVIEW

**Comment by tristanbollard** [comment]
need to fix 
```
Fatal: overlay.mk: Not all overlays are listed in overlay.mk
107c107
< treble-overlay-samsung-a20
```

it's in the overlay file...

**Comment by wmdhs12138** [comment]
Pay attention to letter case

**Comment by tristanbollard** [comment]
> Pay attention to letter case

But it seems to be correctly cased. What's not cased?

**Comment by wmdhs12138** [comment]
Maybe you can try
 
android:requiredSystemPropertyValue=​"​+*samsung/a20*​"
Change to 
android:requiredSystemPropertyValue=​"​+*Samsung/A20*​"

**Comment by tristanbollard** [comment]
> Maybe you can try
> 
> android:requiredSystemPropertyValue=​"​+_samsung/a20_​" Change to android:requiredSystemPropertyValue=​"​+_Samsung/A20_​"

tried that it just doesn't work with this....

**Comment by wmdhs12138** [comment]
And then edit all  'a20' to 'A20' in the files.

**Comment by tristanbollard** [comment]
Doesn't seem to be working no matter what I keep getting stuck on...

```
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/fd7b3a72-b237-40d9-9749-54a340bb9968.sh
Warning: ./Gestures: Overlay ./Gestures is defining config_swipe_up_gesture_setting_available which is forbidden
Warning: ./Moto/G6Plus/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Warning: ./Moto/E5/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Warning: ./Moto/G7Power/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Warning: ./Moto/Razr/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Warning: ./Moto/G6/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Warning: ./Moto/E5Plus/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Warning: ./Moto/One/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Warning: ./Moto/G6Play/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Warning: ./Moto/G7Play/AndroidManifest.xml: ro.vendor.product.* is deprecated. Please use ro.vendor.build.fingerprint
Note: First high continuous priority available is 950
	I recommend you use priority 279
Fatal: overlay.mk: Not all overlays are listed in overlay.mk
114c114
< treble-overlay-samsung-a20
---
> treble-overlay-samsung-a20
##[error]Bash exited with code '1'.
Finishing: Running test scripts
```

It seems to be failing around `diff $a $b` So i'm not to sure.

**Comment by phhusson** [comment]
Merged in https://github.com/phhusson/vendor_hardware_overlay/commit/31c49087d5b5ffe4bb914370cc7251a894950b84

**Pull request closed without merging**
