### PR TITLE
Fix product name

### PR DESCRIPTION
**Pull request by GodcraftPlata**
So yeah, almost nobody uses GSIs on Hannah, so I think is better to use Rhannah product name

### CODE REVIEW

**Comment by phhusson** [comment]
what? if you need both just do `+*hannah`

**Comment by GodcraftPlata** [comment]
oh okay then

**Comment by GodcraftPlata** [comment]
like this?

**Comment by phhusson** [comment]
Yeah. Please confirm it works for you.

Le sam. 8 févr. 2020 à 23:30, GodcraftPlata <notifications@github.com> a
écrit :

**Comment by GodcraftPlata** [comment]
Working

**Pull request merged**
