### PR TITLE
Update notch support

### PR DESCRIPTION
**Pull request by TadiT7**

### CODE REVIEW

**Comment by TadiT7** [comment]
uh xD

**Comment by TadiT7** [comment]
Ping ping @phhusson

**Comment by phhusson** [comment]
So config_mainBuiltInDisplayCutout is the real hardware thing, and was correct in your initial commit
but to "expand touchable area", you decided to make it bigger, and now you decide to set it to hardware size?
Or initial values of status_bar_height and config_mainBuiltInDisplayCutout were simply cherry-picked from OEM?

**Comment by TadiT7** [comment]
Tested on actual tulip. Looks well, but the huge notch lets us to fit only one notification icon. Or rather AOSP won't let us keep them denser. Treat as finished.

**Pull request merged**
